Fix csv_file argument type in load_test.py
Remote functions doesn't allow `Pathlib._local` module. This PR converts `csv_file` argument to string. 

### Error:
```
modal.exception.DeserializationError: Deserialization failed because the 'pathlib._local' module is not available in the remote environment.
```