fix: set default environment for local `load_test.py` (#1144)
Right now running `modal run openai_compatible/load_test.py` as instructed on
https://modal.com/docs/examples/vllm_inference#testing-the-server fails with
`InvalidError: Image ENV variables must be strings. Invalid keys:
['MODAL_ENVIRONMENT']`.

This happens when `environment` is `None`. Users reading these docs may not
have configured a modal environment yet. This change uses an empty string as
the fallback which is consistent with
`06_gpu_and_ml/llm-serving/openai_compatible/client.py`.

```bash
$ modal run openai_compatible/load_test.py
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/dxia/src/github.com/modal-labs/modal-examples/06_gpu_and_ml/llm-serving/openai_compatible │
│ /load_test.py:18 in <module>                                                                     │
│                                                                                                  │
│   17 │   .pip_install("locust~=2.29.1", "openai~=1.37.1")                                        │
│ ❱ 18 │   .env({"MODAL_WORKSPACE": workspace, "MODAL_ENVIRONMENT": environment})                  │
│   19 │   .add_local_file(                                                                        │
│                                                                                                  │
│ /Users/dxia/.pyenv/versions/3.13.3/envs/modal-examples/lib/python3.13/site-packages/modal/image. │
│ py:2002 in env                                                                                   │
│                                                                                                  │
│   2001 │   │   if non_str_keys:                                                                  │
│ ❱ 2002 │   │   │   raise InvalidError(f"Image ENV variables must be strings. Invalid keys: {non  │
│   2003                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
InvalidError: Image ENV variables must be strings. Invalid keys: ['MODAL_ENVIRONMENT']
```

We also fix the host string to take the environment into account. This is
consistent with `06_gpu_and_ml/llm-serving/openai_compatible/client.py` too.
Currently, `modal run openai_compatible/load_test.py` also results in this error.

```
[2025-04-26 20:49:14,561] modal/INFO/locust.runners: Sending spawn jobs of 36 users at 1.00 spawn rate to 8 ready workers
[2025-04-26 20:49:14,752] modal/ERROR/locust.user.task: 404 Client Error: Not Found for url: https://davidxia---example-vllm-openai-compatible-serve.modal.run/v1/chat/completions
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/usr/local/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/root/locustfile.py", line 35, in chat_completion
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://davidxia---example-vllm-openai-compatible-serve.modal.run/v1/chat/completions
```

Signed-off-by: David Xia <david@davidxia.com>