refactor: use `urllib` instead of `requests` in local code for sgl_vlm.py (#1149)
* refactor: use `urllib` instead of `requests` in local code for sgl_vlm.py

User may not have `requests` installed.

Fix some type checks.

Make server return the answer as that seems like a more likely and useful
behavior than server only printing results to logs.

Signed-off-by: David Xia <david@davidxia.com>

* fix: pin `sgl-kernel` to 0.1.0

Maintainers released [0.1.1 on 2025-04-30][1].
Without this pin, the newer version is installed.
0.1.1 causes the app to crash at runtime with this error.

```
Traceback (most recent call last):
  File "/pkg/modal/_runtime/container_io_manager.py", line 704, in handle_user_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 369, in call_lifecycle_functions
    res = func(*args)
          ^^^^^^^^^^^
  File "/root/sgl_vlm.py", line 127, in start_runtime
    self.runtime = sgl.Runtime(
                   ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sglang/api.py", line 39, in Runtime
    from sglang.srt.server import Runtime
  File "/usr/local/lib/python3.11/site-packages/sglang/srt/server.py", line 47, in <module>
    from sglang.srt.managers.data_parallel_controller import (
  File "/usr/local/lib/python3.11/site-packages/sglang/srt/managers/data_parallel_controller.py", line 25, in <module>
    from sglang.srt.managers.io_struct import (
  File "/usr/local/lib/python3.11/site-packages/sglang/srt/managers/io_struct.py", line 24, in <module>
    from sglang.srt.managers.schedule_batch import BaseFinishReason
  File "/usr/local/lib/python3.11/site-packages/sglang/srt/managers/schedule_batch.py", line 40, in <module>
    from sglang.srt.configs.model_config import ModelConfig
  File "/usr/local/lib/python3.11/site-packages/sglang/srt/configs/model_config.py", line 24, in <module>
    from sglang.srt.layers.quantization import QUANTIZATION_METHODS
  File "/usr/local/lib/python3.11/site-packages/sglang/srt/layers/quantization/__init__.py", line 25, in <module>
    from sglang.srt.layers.quantization.fp8 import Fp8Config
  File "/usr/local/lib/python3.11/site-packages/sglang/srt/layers/quantization/fp8.py", line 31, in <module>
    from sglang.srt.layers.moe.fused_moe_triton.fused_moe import padding_size
  File "/usr/local/lib/python3.11/site-packages/sglang/srt/layers/moe/fused_moe_triton/__init__.py", line 4, in <module>
    import sglang.srt.layers.moe.fused_moe_triton.fused_moe  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sglang/srt/layers/moe/fused_moe_triton/fused_moe.py", line 14, in <module>
    from sgl_kernel import moe_align_block_size as sgl_moe_align_block_size
  File "/usr/local/lib/python3.11/site-packages/sgl_kernel/__init__.py", line 13, in <module>
    from sgl_kernel import common_ops
ImportError: /usr/local/lib/python3.11/site-packages/sgl_kernel/common_ops.abi3.so: undefined symbol: _ZNK3c1011StorageImpl27throw_data_ptr_access_errorEv
Runner failed with exception: ImportError('/usr/local/lib/python3.11/site-packages/sgl_kernel/common_ops.abi3.so: undefined symbol: _ZNK3c1011StorageImpl27throw_data_ptr_access_errorEv')
```

[1]: https://pypi.org/project/sgl-kernel/0.1.1/#history

Signed-off-by: David Xia <david@davidxia.com>

---------

Signed-off-by: David Xia <david@davidxia.com>